setup of the framework
TA-Crash-Course-Autumn-2021/opencart_team_1 pull request #2
Opened 2021-11-09 21:01 UTC by Lilia-k-2

2021-11-09 21:39 UTC, MihayloKsyongik26 approved these changes

2021-11-09 23:20 UTC, Selengiks approved these changes

2021-11-09 23:50 UTC, MihayloKsyongik26 approved these changes

2021-11-10 11:44 UTC, MihayloKsyongik26 approved these changes
very good

2021-11-10 11:47 UTC, Selengiks requested changes
approved

2021-11-10 11:52 UTC, Selengiks approved these changes
Approve?

2021-11-10 13:53 UTC, merged